import type { Card, Deck } from '../entities/types';

const seedDate = '2026-06-01T09:00:00.000Z';

export const seedDecks: Deck[] = [
  {
    id: 'spanish',
    title: 'Spanish',
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'french',
    title: 'French',
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'english',
    title: 'English',
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'it-terms',
    title: 'IT Terms',
    createdAt: seedDate,
    updatedAt: seedDate,
  },
];

export const seedCards: Card[] = [
  {
    id: 'card-spanish-rana',
    deckId: 'spanish',
    word: 'la rana',
    translation: 'frog',
    example: 'La rana salta cerca del lago.',
    comment: 'Used for the animal and as a cute app mascot.',
    status: 'new',
    isHidden: false,
    reviewCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrectCount: 0,
    consecutiveWrongCount: 0,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'card-spanish-recordar',
    deckId: 'spanish',
    word: 'recordar',
    translation: 'to remember',
    example: 'Quiero recordar esta palabra.',
    comment: 'Regular -ar verb, useful in daily speech.',
    status: 'learning',
    isHidden: false,
    reviewCount: 1,
    correctCount: 1,
    wrongCount: 0,
    consecutiveCorrectCount: 1,
    consecutiveWrongCount: 0,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'card-spanish-mazo',
    deckId: 'spanish',
    word: 'el mazo',
    translation: 'deck',
    example: 'Tengo un mazo nuevo.',
    comment: 'Also means a bundle or stack, depending on context.',
    status: 'review',
    isHidden: false,
    reviewCount: 4,
    correctCount: 4,
    wrongCount: 0,
    consecutiveCorrectCount: 4,
    consecutiveWrongCount: 0,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'card-english-focus',
    deckId: 'english',
    word: 'focus',
    translation: 'concentrarse',
    example: 'I need to focus on this word.',
    comment: 'Useful daily verb.',
    status: 'new',
    isHidden: false,
    reviewCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrectCount: 0,
    consecutiveWrongCount: 0,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
  {
    id: 'card-it-cache',
    deckId: 'it-terms',
    word: 'cache',
    translation: 'temporary storage',
    example: 'The browser stores files in cache.',
    comment: 'Common backend/frontend term.',
    status: 'mastered',
    isHidden: false,
    nextReviewAt: '2026-05-30T09:00:00.000Z',
    lastReviewedAt: '2026-05-16T09:00:00.000Z',
    reviewCount: 10,
    correctCount: 9,
    wrongCount: 1,
    consecutiveCorrectCount: 2,
    consecutiveWrongCount: 0,
    createdAt: seedDate,
    updatedAt: seedDate,
  },
];
